//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongLyrics.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongLyrics.Shared.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are no albums on the list.
        /// </summary>
        public static string EMPTY_ALBUM_LIST {
            get {
                return ResourceManager.GetString("EMPTY_ALBUM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no songs listed for given Album Id.
        /// </summary>
        public static string EMPTY_ALBUM_SONGS_LIST {
            get {
                return ResourceManager.GetString("EMPTY_ALBUM_SONGS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given band have no albums listed.
        /// </summary>
        public static string EMPTY_BAND_ALBUMS_LIST {
            get {
                return ResourceManager.GetString("EMPTY_BAND_ALBUMS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bands on the list.
        /// </summary>
        public static string EMPTY_BAND_LIST {
            get {
                return ResourceManager.GetString("EMPTY_BAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given band has no members listed.
        /// </summary>
        public static string EMPTY_MEMBERS_LIST {
            get {
                return ResourceManager.GetString("EMPTY_MEMBERS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are no songs on the list.
        /// </summary>
        public static string EMPTY_SONG_LIST {
            get {
                return ResourceManager.GetString("EMPTY_SONG_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no album for given Album Id.
        /// </summary>
        public static string NO_ALBUM_FOUND {
            get {
                return ResourceManager.GetString("NO_ALBUM_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The is no song for given Song Id.
        /// </summary>
        public static string NO_SONG_FOUND {
            get {
                return ResourceManager.GetString("NO_SONG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
